### ISSUE TITLE
Consolidate all YNAB converter scripts into one?

### ISSUE THREAD

**Issue by nocalla** [abesto/otp2ynab#1]
Hi @abesto,

I've noticed that there are more than 80 GitHub projects related to YNAB converter scripts. https://github.com/search?q=ynab+convert&type=Repositories&utf8=%E2%9C%93

--> Would it be helpful and would there be interest in an effort to consolidate all (most) of these into a single tool?

On the plus side, clearly there's more than enough solutions and contributors. On the minus side, these are spread across different spoken languages, programming languages, and of course bank export formats.

We've developed a fairly robust solution over at [Bank2YNAB](https://github.com/torbengb/bank2ynab) and are looking for help from the developers of the original scripts to add formats for the different banks that are currently supported by different projects on Github.

We'd like to include this bank in our configuration file, but we lack a sample data set to use. If you have time, we'd love to hear from you over on the [OTP](https://github.com/torbengb/bank2ynab/issues/136) issue, either for an explanation of the source data or an (anonymised!) sample input file.

Regards from Ireland,

Niall

**Comment by abesto** [comment]
Oh wow, I'm impressed. Let me hop over and provide some details.

Closing this to track in a single place.
